// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.agileways.forces.machine.agv;
import java.rmi.server.ObjID;

public final class AgvRegistryImplBase_Stub
    extends java.rmi.server.RemoteStub
    implements com.agileways.forces.machine.agv.AgvRegistry, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_lookup_0;
    private static java.lang.reflect.Method $method_rebind_1;
    
    static {
	try {
	    $method_lookup_0 = com.agileways.forces.machine.agv.AgvRegistry.class.getMethod("lookup", new java.lang.Class[] {java.lang.String.class});
	    $method_rebind_1 = com.agileways.forces.machine.agv.AgvRegistry.class.getMethod("rebind", new java.lang.Class[] {java.lang.String.class, com.agileways.forces.machine.agv.AGV.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public AgvRegistryImplBase_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of lookup(String)
    public com.agileways.forces.machine.agv.AGV lookup(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_lookup_0, new java.lang.Object[] {$param_String_1}, -7416405800998551684L);
	    return ((com.agileways.forces.machine.agv.AGV) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of rebind(String, AGV)
    public void rebind(java.lang.String $param_String_1, com.agileways.forces.machine.agv.AGV $param_AGV_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_rebind_1, new java.lang.Object[] {$param_String_1, $param_AGV_2}, -7212722143970017496L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
