// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package net.agileframes.traces.ticket;

public final class PrimeTicketRemoteImpl_Stub
    extends java.rmi.server.RemoteStub
    implements net.agileframes.traces.ticket.PrimeTicketRemote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_setAssigned_0;
    
    static {
	try {
	    $method_setAssigned_0 = net.agileframes.traces.ticket.PrimeTicketRemote.class.getMethod("setAssigned", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public PrimeTicketRemoteImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of setAssigned()
    public void setAssigned()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setAssigned_0, null, 5906652584182766721L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
