// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package net.agileframes.traces;

public final class RemoteSceneListener_Stub
    extends java.rmi.server.RemoteStub
    implements net.jini.core.event.RemoteEventListener
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_notify_0;
    
    static {
	try {
	    $method_notify_0 = net.jini.core.event.RemoteEventListener.class.getMethod("notify", new java.lang.Class[] {net.jini.core.event.RemoteEvent.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RemoteSceneListener_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of notify(RemoteEvent)
    public void notify(net.jini.core.event.RemoteEvent $param_RemoteEvent_1)
	throws java.rmi.RemoteException, net.jini.core.event.UnknownEventException
    {
	try {
	    ref.invoke(this, $method_notify_0, new java.lang.Object[] {$param_RemoteEvent_1}, 1042791172444620860L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (net.jini.core.event.UnknownEventException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
