// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package net.agileframes.traces.viewer;

public final class SemaphoreViewer_Stub
    extends java.rmi.server.RemoteStub
    implements net.agileframes.traces.viewer.SemaphoreViewerRemote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_modelChanged_0;
    
    static {
	try {
	    $method_modelChanged_0 = net.agileframes.traces.viewer.SemaphoreViewerRemote.class.getMethod("modelChanged", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public SemaphoreViewer_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of modelChanged()
    public void modelChanged()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_modelChanged_0, null, -7049089691750945533L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
