// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package net.agileframes.vr.space3d;

public final class Virtuality3D_Stub
    extends java.rmi.server.RemoteStub
    implements net.jini.core.event.RemoteEventListener
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("void notify(net.jini.core.event.RemoteEvent)")
    };
    
    private static final long interfaceHash = -8017186574002926494L;
    
    private static final long serialVersionUID = 2;
    
    private static boolean useNewInvoke;
    private static java.lang.reflect.Method $method_notify_0;
    
    static {
	try {
	    java.rmi.server.RemoteRef.class.getMethod("invoke",
		new java.lang.Class[] {
		    java.rmi.Remote.class,
		    java.lang.reflect.Method.class,
		    java.lang.Object[].class,
		    long.class
		});
	    useNewInvoke = true;
	    $method_notify_0 = net.jini.core.event.RemoteEventListener.class.getMethod("notify", new java.lang.Class[] {net.jini.core.event.RemoteEvent.class});
	} catch (java.lang.NoSuchMethodException e) {
	    useNewInvoke = false;
	}
    }
    
    // constructors
    public Virtuality3D_Stub() {
	super();
    }
    public Virtuality3D_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of notify(RemoteEvent)
    public void notify(net.jini.core.event.RemoteEvent $param_RemoteEvent_1)
	throws java.rmi.RemoteException, net.jini.core.event.UnknownEventException
    {
	try {
	    if (useNewInvoke) {
		ref.invoke(this, $method_notify_0, new java.lang.Object[] {$param_RemoteEvent_1}, 1042791172444620860L);
	    } else {
		java.rmi.server.RemoteCall call = ref.newCall((java.rmi.server.RemoteObject) this, operations, 0, interfaceHash);
		try {
		    java.io.ObjectOutput out = call.getOutputStream();
		    out.writeObject($param_RemoteEvent_1);
		} catch (java.io.IOException e) {
		    throw new java.rmi.MarshalException("error marshalling arguments", e);
		}
		ref.invoke(call);
		ref.done(call);
	    }
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (net.jini.core.event.UnknownEventException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
